sudo: required
language: generic # to prevent some issue as explained in the course
services:
  - docker

before_install:
  - docker build -t jorgesalazar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jorgesalazar/react-test npm test  #fixed command as explained in the course

after_success:
  - docker build -t jorgesalazar/multi-client ./client
  - docker build -t jorgesalazar/multi-nginx ./nginx
  - docker build -t jorgesalazar/multi-server ./server
  - docker build -t jorgesalazar/multi-worker ./worker

# log inn to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take those images and push them to docker hub
  - docker push jorgesalazar/multi-client
  - docker push jorgesalazar/multi-nginx
  - docker push jorgesalazar/multi-server
  - docker push jorgesalazar/multi-worker

